server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.31.39.212:3100/loki/api/v1/push

scrape_configs:
  - job_name: neo4j
    static_configs:
      - targets: [localhost]
        labels:
          job: neo4j
          host: graphdb
          __path__: /var/log/neo4j/*.log
    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<timestamp>\S+ \S+)\s+(?P<level>\w+)\s+(?P<message>.*)'
      - labels:
          level:
